@baseUrl = http://localhost:3000
@postId = 69592f5cf02dc66aa6d290e8
@commentId = 69593447f02dc66aa6d29102

################################
# POSTS
################################

### Create Post
POST {{baseUrl}}/post
Content-Type: application/json

{
  "sender": "shahaf",
  "content": "my first post"
}

###

### Get All Posts
GET {{baseUrl}}/post

###

### Get Posts By Sender
GET {{baseUrl}}/post?sender=shahaf

###

### Get Post By ID
GET {{baseUrl}}/post/{{postId}}

###

### Update Post
PUT {{baseUrl}}/post/{{postId}}
Content-Type: application/json

{
  "content": "updated post content"
}



################################
# COMMENTS
################################

### Create Comment
POST {{baseUrl}}/comment
Content-Type: application/json

{
  "postId":"{{postId}}
  "sender": "tal",
  "text": "my first comment"
}

###

### Get All Comments By Post
GET {{baseUrl}}/comment?postId={{postId}}

###

### Get Comment By Id
GET {{baseUrl}}/comment/{{commentId}}

###

### Update Comment
PUT {{baseUrl}}/comment/{{commentId}}
Content-Type: application/json

{
  "text": "edited comment"
}

###

### Delete Comment
DELETE {{baseUrl}}/comment/{{commentId}}


